[build]
  command = "npm run build"
  publish = "dist"
  base = ""

[build.environment]
  NODE_VERSION = "18"
  VITE_ACCESS_KEY = "Resilium@2025"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
